// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: queries.sql

package db

import (
	"context"
)

const deleteUnusedTags = `-- name: DeleteUnusedTags :exec
DELETE FROM tags    WHERE id NOT IN (SELECT tag_id FROM archives_tags)
`

func (q *Queries) DeleteUnusedTags(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteUnusedTags)
	return err
}
